# Generated by Django 2.2.5 on 2019-11-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shayari',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shayari',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
