# Generated by Django 2.2.5 on 2019-11-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayari', '0002_auto_20191113_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='shayari',
            name='category',
            field=models.CharField(choices=[('MO', 'Motivational'), ('INS', 'Inspirational'), ('SAD', 'Sad'), ('RO', 'Romantic'), ('LI', 'Life'), ('CO', 'Comedy')], default='MO', max_length=20),
        ),
    ]
