# Generated by Django 2.2.5 on 2019-11-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayari', '0003_shayari_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shayari',
            name='category',
            field=models.CharField(choices=[('MOTIVATIONAL', 'Motivational'), ('INSPIRATIONAL', 'Inspirational'), ('SAD', 'Sad'), ('ROMANTIC', 'Romantic'), ('LIFE', 'Life'), ('COMEDY', 'Comedy')], default='MOTIVATIONAL', max_length=20),
        ),
    ]
