# Generated by Django 2.2.5 on 2020-02-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayari', '0005_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shayari',
            name='category',
            field=models.CharField(choices=[('MOTIVATIONAL', 'Motivational'), ('INSPIRATIONAL', 'Inspirational'), ('SAD', 'Sad'), ('ROMANTIC', 'Romantic'), ('LIFE', 'Life'), ('COMEDY', 'Comedy'), ('FRIENDSHIP', 'Friendship')], default='MOTIVATIONAL', max_length=20),
        ),
    ]
